spring:
  datasource:
    #initialization-mode: always
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://postgrestekdev.cd6oucy10xvk.us-east-2.rds.amazonaws.com:5432/postgrestekdev
    username: postgrestek
    password: nbmax123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      max-lifetime: 900000

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

